exports.Constant = {
  SURVIVOR_GENDER_MALE: "MALE",
  SURVIVOR_GENDER_FEMALE: "FEMALE",

  SURVIVOR_IS_INFECTED_Y: 'Y',
  SURVIVOR_IS_INFECTED_N: 'N',

  ITEM_TO_TRADE_WATER: 'WATER',
  ITEM_TO_TRADE_FOOD: 'FOOD',
  ITEM_TO_TRADE_MEDICATION: 'MEDICATION',
  ITEM_TO_TRADE_AMMUNITION: 'AMMUNITION',
  ITEM_TO_TRADE: {
    WATER: 'Water',
    FOOD: 'Food',
    MEDICATION: 'Medication',
    AMMUNITION: 'Ammunition',
  },

  ITEM_POINTS: {
    WATER: 4,
    FOOD: 3,
    MEDICATION: 2,
    AMMUNITION: 1
  },

  TRADE_TYPE_IN: 'IN',
  TRADE_TYPE_OUT: 'OUT',

  SURVIVOR_ITEM_INCREASE: 'INCREASE',
  SURVIVOR_ITEM_DECREASE: 'DECREASE'


}